// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// For more information on how to use Firebase, refer to the documentation:
// https://firebase.google.com/docs/web/setup
export const firebaseConfig = {
  "apiKey": "AIzaSyCVAkH-u-c3v-1-gIzz0c_TCkoLmqA_vw",
  "authDomain": "meetupgo-2024.firebaseapp.com",
  "projectId": "meetupgo-2024",
  "storageBucket": "meetupgo-2024.appspot.com",
  "messagingSenderId": "1004184311186",
  "appId": "1:1004184311186:web:1d63c52e464c12658a0346"
};
