// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// For more information on how to use Firebase, refer to the documentation:
// https://firebase.google.com/docs/web/setup
export const firebaseConfig = {
  apiKey: "AIzaSyA3qdY8UUgynhUzTsl87qkC1QGKd0zGKtc",
  authDomain: "apps-meet.firebaseapp.com",
  projectId: "apps-meet",
  storageBucket: "apps-meet.firebasestorage.app",
  messagingSenderId: "777410946795",
  appId: "1:777410946795:web:b95fb5160c2d69c42b40ae",
  measurementId: "G-GEXTJ5HHFN"
};
